kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: configmap-access
rules:
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "configmaps" ]
    verbs: [ "get", "watch", "list" ,"delete" ]