apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}

  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabel }}
    spec:
      containers:
        - name:  {{ .Values.container.name}}
          image:  {{ .Values.container.image}}
          ports:
            - containerPort: {{ .Values.service.port}}
          env:
            - name: "server.Port"
              value: "{{ .Values.service.port}}"
            - name: "ipfs.Backs"
              value: "{{ .Values.ipfsBacks}}"
